name: flutter_advanced_course_multi_modular_clean_architecture
packages:
  - core/**
  - features/**
#  - features/movies

command:
  bootstrap:
    environment:
      sdk: ^3.5.3
      flutter: ">=1.17.0"

    dependencies:
      dio: ^5.9.0

    dev_dependencies:
      flutter_lints: ^5.0.0